name: Check For Stale Repositories
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

permissions:
  contents: read  #  to fetch code (actions/checkout)

jobs:
  build:
    name: Running test
    runs-on: ubuntu-latest
    container: golang:1.27
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Get dependencies
      run: go mod download
    - name: run script
      run: go test -v -run ^TestStaleRepository$
      env:
        OAUTH_TOKEN: ${{secrets.OAUTH_TOKEN}}
