name: Check For Stale Repositories
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

permissions:
  contents: read  #  to fetch code (actions/checkout)

jobs:
  build:
    name: Running test
    runs-on: ubuntu-latest
    container: golang:1.27
    steps:
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
    - name: Get dependencies
      run: go mod download
    - name: run script
      run: go test -v -run ^TestStaleRepository$
      env:
        OAUTH_TOKEN: ${{secrets.OAUTH_TOKEN}}
