name: tests

on:
  push:
    branches:
      - 'main'
  pull_request:

permissions:
  contents: read  #  to fetch code (actions/checkout)

jobs:
  build:
    name: Running test
    runs-on: ubuntu-latest
    container: golang:1.27
    steps:
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
    - name: Get dependencies
      run: go mod download
    - name: Run tests
      run: go test main_test.go main.go
