name: tests

on:
  push:
    branches:
      - 'main'
  pull_request:

permissions:
  contents: read  #  to fetch code (actions/checkout)

jobs:
  build:
    name: Running test
    runs-on: ubuntu-latest
    container: golang:1.27
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Get dependencies
      run: go mod download
    - name: Run tests
      run: go test main_test.go main.go
